[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023725A4DA60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/acbc2adb-abf3-47ed-88b5-45e0e45822a4
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023725A4D430>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/acbc2adb-abf3-47ed-88b5-45e0e45822a4
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:872 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023725A4E5D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/acbc2adb-abf3-47ed-88b5-45e0e45822a4